-- ===================================================
-- SQL Schema & Seed Data for ZeeVerlyn Supabase Database
-- Run this script in your Supabase SQL Editor:
-- https://app.supabase.com -> Project -> SQL Editor
-- ===================================================

-- 1. Table: Gallery
CREATE TABLE IF NOT EXISTS public.gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caption TEXT NOT NULL,
  image TEXT,
  tag TEXT DEFAULT 'dates',
  color TEXT DEFAULT '#f4a6c1',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: Timeline
CREATE TABLE IF NOT EXISTS public.timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT,
  icon TEXT DEFAULT 'favorite',
  is_highlight BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: Playlist
CREATE TABLE IF NOT EXISTS public.playlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  link TEXT NOT NULL,
  cover_image TEXT,
  cover_color TEXT DEFAULT '#ff6fa5',
  duration TEXT DEFAULT '3:30',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: Letters
CREATE TABLE IF NOT EXISTS public.letters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  greeting TEXT NOT NULL,
  paragraphs JSONB NOT NULL,
  closing TEXT DEFAULT 'With all my love,',
  signature TEXT DEFAULT 'Zidane 💕',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table: Favorites
CREATE TABLE IF NOT EXISTS public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  emoji TEXT DEFAULT '🕷️',
  avatar TEXT,
  favorite_color TEXT DEFAULT '#f4a6c1',
  favorite_song TEXT,
  favorite_food TEXT,
  fun_fact TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) and allow public read & write access
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Gallery" ON public.gallery FOR SELECT USING (true);
CREATE POLICY "Public Write Gallery" ON public.gallery FOR ALL USING (true);

CREATE POLICY "Public Read Timeline" ON public.timeline FOR SELECT USING (true);
CREATE POLICY "Public Write Timeline" ON public.timeline FOR ALL USING (true);

CREATE POLICY "Public Read Playlist" ON public.playlist FOR SELECT USING (true);
CREATE POLICY "Public Write Playlist" ON public.playlist FOR ALL USING (true);

CREATE POLICY "Public Read Letters" ON public.letters FOR SELECT USING (true);
CREATE POLICY "Public Write Letters" ON public.letters FOR ALL USING (true);

-- Enable Realtime for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.gallery;
ALTER PUBLICATION supabase_realtime ADD TABLE public.timeline;
ALTER PUBLICATION supabase_realtime ADD TABLE public.playlist;
ALTER PUBLICATION supabase_realtime ADD TABLE public.letters;
ALTER PUBLICATION supabase_realtime ADD TABLE public.favorites;

-- Initial Seed Data: Gallery
INSERT INTO public.gallery (caption, image, tag) VALUES
  ('Our first trip together 🤍', '/images/gallery/photo-1.jpg', 'travel'),
  ('Random cute moment', '/images/gallery/photo-2.jpg', 'random'),
  ('Anniversary dinner', '/images/gallery/photo-3.jpg', 'dates');

-- Initial Seed Data: Timeline
INSERT INTO public.timeline (title, date, description, image, icon, is_highlight) VALUES
  ('Pertama Kali Ketemu', '2025-08-15', 'Hari pertama kita mengobrol dan kenalan, rasanya seperti spider-sense langsung bergetar! ✨', null, 'star', false),
  ('First Date Spot', '2025-09-20', 'Jalan-jalan pertama bareng, minum kopi dan cerita panjang lebar sampai lupa waktu. ☕', null, 'local_cafe', false),
  ('Hari Spesial Jadian! 💕', '2026-01-07', 'Hari di mana kita meresmikan perjalanan cinta kita bersama di Spider-Verse ini. 🕸️✨', null, 'favorite', true);

-- Initial Seed Data: Playlist
INSERT INTO public.playlist (title, artist, link, duration) VALUES
  ('Sunflower', 'Post Malone, Swae Lee', 'https://open.spotify.com', '2:38'),
  ('Until I Found You', 'Stephen Sanchez', 'https://open.spotify.com', '2:57'),
  ('Double Take', 'dhruv', 'https://open.spotify.com', '2:51');

-- Initial Seed Data: Letters
INSERT INTO public.letters (greeting, paragraphs, closing, signature) VALUES
  (
    'Dear Verlita 💕,',
    '[
      "Sejak pertama kali kita bertemu, hidupku terasa jauh lebih berwarna dan penuh kejutan manis.",
      "Sama seperti Spider-Man yang selalu menemukan jalan pulang, aku tahu bahwa sejauh apapun aku melangkah, hatiku akan selalu kembali padamu.",
      "Terima kasih sudah menjadi bagian terindah dalam ceritaku. I love you across every universe! 🕸️✨"
    ]',
    'Forever & Always,',
    'Zidane 🕸️'
  );
